##Plot 3
data <- read.csv("C:/Users/Edward Wang/Desktop/household_power_consumption.txt", sep=";", na.strings="?")
newdata <- rbind(data[data$Date == "1/2/2007",], data[data$Date == "2/2/2007",])
plot(newdata$Sub_metering_1, type = "l", col = "black", axes = F, xlab = "", ylab = "Energy sub metering")
lines(newdata$Sub_metering_2, type="l",  col="red")
lines(newdata$Sub_metering_3, type="l",  col="blue")
axis(1, at=seq(0,2880,1440), labels=c("Thu","Fri","Sat"))
axis(2)
box()
legend("topright", lwd = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex = 0.6)
dev.copy(png, file = "plot3.png")
dev.off()